---
# tasks file for role_deploy_jar
#- name: get the war
#  get_url:
#  url: git@gitlab.com:RaphaeldeGail/devopsapp.git
#  dest: /tmp
     
#- name: 


#- name: extract the war
#  unarchive:
#      src=/tmp/devopsapp.git
#      copy=no
#      dest=/tmp
  

 
 ####### Role non abouti
